export const patients = [
  {
    id: 1,
    name: "John Smith",
    age: 45,
    gender: "Male",
    phone: "(555) 123-4567",
    email: "john.smith@example.com",
    lastVisit: "2 days ago",
    nextAppointment: "Tomorrow, 10:30 AM",
    status: "Active",
  },
  {
    id: 2,
    name: "Emma Johnson",
    age: 32,
    gender: "Female",
    phone: "(555) 234-5678",
    email: "emma.johnson@example.com",
    lastVisit: "1 week ago",
    nextAppointment: "Next Friday, 2:15 PM",
    status: "Active",
  },
  {
    id: 3,
    name: "David Lee",
    age: 28,
    gender: "Male",
    phone: "(555) 345-6789",
    email: "david.lee@example.com",
    lastVisit: "Today",
    nextAppointment: "May 15, 11:00 AM",
    status: "Active",
  },
  {
    id: 4,
    name: "Sarah Wilson",
    age: 37,
    gender: "Female",
    phone: "(555) 456-7890",
    email: "sarah.wilson@example.com",
    lastVisit: "3 days ago",
    nextAppointment: "Not scheduled",
    status: "Inactive",
  },
];
