// appointmentsData.js
const AppointmentsData = [
  {
    id: 1,
    patient: "John Doe",
    patientId: "PT-0025",
    doctor: "Dr. Robert Wilson",
    specialty: "Cardiology",
    date: "2023-11-28",
    time: "10:00 AM ",
    type: "Follow-up",
    paymentStatus: "Online",
    status: "Confirmed",
  },
  {
    id: 2,
    patient: "Jane Smith",
    patientId: "PT-0026",
    doctor: "Dr. Lisa Martinez",
    specialty: "Neurology",
    date: "2023-11-27",
    time: "11:30 AM ",
    type: "New Patient",
    paymentStatus: "Pending",
    status: "Pending",
  },
  {
    id: 3,
    patient: "Robert Johnson",
    patientId: "PT-0027",
    doctor: "Dr. Michael Chen",
    specialty: "Orthopedics",
    date: "2023-11-27",
    time: "2:00 PM ",
    type: "Post-op",
    paymentStatus: "Online",
    status: "Confirmed",
  },
  {
    id: 4,
    patient: "Emily Williams",
    patientId: "PT-0028",
    doctor: "Dr. Sarah Garcia",
    specialty: "Pediatrics",
    date: "2023-11-28",
    time: "3:30 PM ",
    type: "Check-up",
    paymentStatus: "Cancelled",
    status: "Cancelled",
  },
  {
    id: 5,
    patient: "Jane Smith",
    patientId: "PT-0026",
    doctor: "Dr. Lisa Martinez",
    specialty: "Neurology",
    date: "2023-11-27",
    time: "11:30 AM ",
    type: "New Patient",
    paymentStatus: "Pending",
    status: "Pending",
  },
  {
    id: 6,
    patient: "Robert Johnson",
    patientId: "PT-0027",
    doctor: "Dr. Michael Chen",
    specialty: "Orthopedics",
    date: "2023-11-25",
    time: "2:00 PM ",
    type: "Post-op",
    paymentStatus: "Online",
    status: "Confirmed",
  },
  {
    id: 7,
    patient: "Emily Williams",
    patientId: "PT-0028",
    doctor: "Dr. Sarah Garcia",
    specialty: "Pediatrics",
    date: "2023-11-25",
    time: "3:30 PM ",
    type: "Check-up",
    paymentStatus: "Cancelled",
    status: "Cancelled",
  },
  {
    id: 8,
    patient: "Jane Smith",
    patientId: "PT-0026",
    doctor: "Dr. Lisa Martinez",
    specialty: "Neurology",
    date: "2023-11-28",
    time: "11:30 AM ",
    type: "New Patient",
    paymentStatus: "Pending",
    status: "Pending",
  },
  {
    id: 9,
    patient: "Robert Johnson",
    patientId: "PT-0027",
    doctor: "Dr. Michael Chen",
    specialty: "Orthopedics",
    date: "2023-12-2",
    time: "2:00 PM ",
    type: "Post-op",
    paymentStatus: "Online",
    status: "Confirmed",
  },
  {
    id: 10,
    patient: "Emily Williams",
    patientId: "PT-0028",
    doctor: "Dr. Sarah Garcia",
    specialty: "Pediatrics",
    date: "2023-12-2",
    time: "3:30 PM ",
    type: "Check-up",
    paymentStatus: "Cancelled",
    status: "Cancelled",
  },
];

export default AppointmentsData;
